version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./psqldata:/var/lib/postgresql/data
    expose:
      - 5432
  # redis:
  #   image: redis
  #   container_name: redis
  #   restart: always
  #   ports:
  #     - "6379:6379"
  #   volumes:
  #     - ./redis-data:/data